let score=0, possible=0, currentQuestion=null;

const banks = {
  polar: [
    {
      prompt: "The polar curve is $$r=2+2\\sin\\theta$$",
      parts: [
        { q: "(a) Find r when θ=π/2", a: "4" },
        { q: "(b) Find the enclosed area.", a: "6*pi" },
        { q: "(c) Is the tangent horizontal, vertical, or neither at θ=π/2?", a: "horizontal" }
      ]
    },
    {
      prompt: "Consider the polar curve $$r = 1 + 2\\cos\\theta$$ (an inner-loop limacon).",
      parts: [
        { q: "(a) Find the values of \\theta in [0, 2\\pi] where the curve passes through the pole (r = 0).", a: "2*pi/3, 4*pi/3" },
        { q: "(b) What is the upper limit of integration used to find the area of the inner loop if the lower limit is 2*pi/3?", a: "4*pi/3" },
        { q: "(c) Find the exact slope of the tangent line to the curve at \\theta = \\pi/2.", a: "1/2" }
      ]
    },
    {
      prompt: "Consider the classic rose curve given by $$r = \\sin(3\\theta)$$.",
      parts: [
        { q: "(a) How many petals does this rose curve have?", a: "3" },
        { q: "(b) Find the total area enclosed by all the petals.", a: "pi/4" },
        { q: "(c) Find the smallest positive value of \\theta where the tangent line is horizontal.", a: "pi/6" }
      ]
    },
    {
      prompt: "Consider the polar curve $$r = \\sin(2\\theta)$$ on the interval $$[0, 2\\pi]$$.",
      parts: [
        { q: "(a) How many petals does this rose curve have?", a: "4" },
        { q: "(b) If you integrate the area formula from 0 to 2*pi, how many petals worth of area do you calculate?", a: "4" },
        { q: "(c) TRICK: If you change the curve to r = sin(3*theta) and integrate from 0 to 2*pi, how many times does the curve trace over itself?", a: "2" }
      ]
    },
    {
      prompt: "Find the total area of the region enclosed by the graph of $$r = -2\\cos\\theta$$.",
      parts: [
        { q: "(a) TRICK: What geometric shape is this curve?", a: "circle" },
        { q: "(b) What is the length of the interval of \\theta required to trace this shape exactly once?", a: "pi" },
        { q: "(c) What is the final enclosed area?", a: "pi" }
      ]
    }
  ],
  
  parametric: [
    {
      prompt: "$$x=t^2+1,\\; y=t^3$$",
      parts: [
        { q: "(a) Find dy/dt at t=2", a: "12" },
        { q: "(b) Find dx/dt at t=2", a: "4" },
        { q: "(c) Find dy/dx at t=2", a: "3" }
      ]
    },
    {
      prompt: "A particle moves along a curve defined by $$x = e^{2t} - 4t,\\; y = 8e^t$$.",
      parts: [
        { q: "(a) Find the value of t where the tangent line to the path is completely vertical.", a: "ln(2)/2" },
        { q: "(b) Find the value of the second derivative d^2y/dx^2 at t=0.", a: "-2/27" },
        { q: "(c) Find the total arc length of the curve from t = 0 to t = 1.", a: "e^2 + 2" }
      ]
    },
    {
      prompt: "Consider the parametric equations representing a cycloid: $$x = t - \\sin t,\\; y = 1 - \\cos t$$.",
      parts: [
        { q: "(a) Evaluate dy/dx at t = \\pi/2.", a: "1" },
        { q: "(b) Evaluate the limit of dy/dx as t approaches 0 from the right.", a: "0" },
        { q: "(c) Find the surface area generated by revolving this curve from t = 0 to t = pi about the x-axis.", a: "64*pi/3" }
      ]
    },
    {
      prompt: "Let a curve be defined by $$x = \\sin(t),\\; y = \\cos^2(t)$$ for $$t \\in [0, 4\\pi]$$.",
      parts: [
        { q: "(a) Eliminate the parameter to find y as a function of x.", a: "y = 1 - x^2" },
        { q: "(b) TRICK: What is the maximum value that x can ever achieve on this curve?", a: "1" },
        { q: "(c) TRICK: How many times does the particle travel back and forth along its path from t = 0 to t = 4*pi?", a: "4" }
      ]
    },
    {
      prompt: "Consider the curve given by $$x = t^3 - 3t,\\; y = t^2$$.",
      parts: [
        { q: "(a) Find the y-coordinate where the curve crosses itself (the self-intersection point).", a: "3" },
        { q: "(b) Find the positive slope of the two tangent lines at this point of self-intersection.", a: "sqrt(3)/3" }
      ]
    }
  ],
  
  ibp: [
    {
      prompt: "Evaluate $$\\int xe^x\\,dx$$",
      parts: [
        { q: "(a) Choose u", a: "x" },
        { q: "(b) Choose dv", a: "e^x" },
        { q: "(c) Final antiderivative", a: "x*e^x-e^x" }
      ]
    },
    {
      prompt: "Evaluate the integral $$\\int e^{2x} \\sin(3x) \\, dx$$ (the secret 'loop-around' IBP).",
      parts: [
        { q: "(a) If you choose u = \\sin(3x) and dv = e^{2x}dx, what is v?", a: "e^(2x)/2" },
        { q: "(b) After applying integration by parts twice, what fractional multiplier balances out the original integral?", a: "13/4" },
        { q: "(c) What is the final antiderivative (excluding + C)?", a: "(e^(2x)/13)*(2*sin(3x) - 3*cos(3x))" }
      ]
    },
    {
      prompt: "Evaluate the integral $$\\int \\ln(x^2 + 1) \\, dx$$",
      parts: [
        { q: "(a) Identify the optimal choice for u.", a: "ln(x^2 + 1)" },
        { q: "(b) After applying the first IBP step, what is the antiderivative of the remaining v*du term?", a: "2x - 2*arctan(x)" },
        { q: "(c) What is the final antiderivative of the original integral (excluding + C)?", a: "x*ln(x^2 + 1) - 2x + 2*arctan(x)" }
      ]
    },
    {
      prompt: "Evaluate $$\\int \\sec^3(x) \\, dx$$.",
      parts: [
        { q: "(a) Identify the traditional choice for dv.", a: "sec^2(x)" },
        { q: "(b) TRICK: After rewriting with a identity, what power of secant reappears to trigger a looping reduction?", a: "3" },
        { q: "(c) What is the final antiderivative (excluding + C)?", a: "1/2*(sec(x)*tan(x) + ln(sec(x) + tan(x)))" }
      ]
    },
    {
      prompt: "Evaluate $$\\int_{1}^{e} x^2 (\\ln x)^2 \\, dx$$.",
      parts: [
        { q: "(a) How many applications of integration by parts are required?", a: "2" },
        { q: "(b) TRICK: If a student accidentally sets u = x^2, will the power of the log term increase, decrease, or stay the same in the next integral?", a: "increase" },
        { q: "(c) What is the exact evaluated value of the definite integral?", a: "(5*e^3 - 2)/27" }
      ]
    }
  ],

  series: [
    {
      prompt: "Let $$f(x) = \\sum_{n=0}^{\\infty} \\frac{(-1)^n x^{2n+1}}{(2n+1)!}$$. We define $$g(x) = \\int f(x) \\, dx$$ with $$g(0) = 1$$.",
      parts: [
        { q: "(a) Find the first two non-zero terms of the series representation for g(x).", a: "1 - x^2/2" },
        { q: "(b) Identify the familiar elementary function that g(x) represents.", a: "cos(x)" },
        { q: "(c) What is the radius of convergence of g(x)?", a: "infinity" }
      ]
    },
    {
      prompt: "Consider the geometric series representation: $$\\frac{1}{1-x} = \\sum_{n=0}^{\\infty} x^n$$ for $$|x| < 1$$.",
      parts: [
        { q: "(a) Find the first three terms of the power series for h(x) = 1/(1-x)^2 by taking a derivative.", a: "1 + 2*x + 3*x^2" },
        { q: "(b) Use your derivative series to evaluate the exact value of the infinite sum 1 + 2/3 + 3/9 + 4/27 + ...", a: "9/4" },
        { q: "(c) TRICK: Does the derivative series converge or diverge at the endpoint x = -1?", a: "diverge" }
      ]
    },
    {
      prompt: "Let $$f(x) = \\ln(1+x) = \\sum_{n=1}^{\\infty} \\frac{(-1)^{n-1}x^n}{n}$$ for $$-1 < x \\le 1$$. We approximate $$\\ln(1.5)$$ using the first 3 terms of this series.",
      parts: [
        { q: "(a) Calculate the fractional approximation of ln(1.5) using the 3rd-degree Taylor polynomial.", a: "5/12" },
        { q: "(b) According to the Alternating Series Estimation Theorem, what is the maximum error bound for this approximation?", a: "1/64" },
        { q: "(c) TRICK: Can we use this exact same series formulation to calculate ln(3)? Type yes or no.", a: "no" }
      ]
    },
    {
      prompt: "Let $$f(x) = \\sum_{n=1}^{\\infty} \\frac{x^n}{n^2}$$. Consider its derivative $$f'(x)$$.",
      parts: [
        { q: "(a) Find the general term (in terms of n and x) of the derivative series f'(x).", a: "x^(n-1)/n" },
        { q: "(b) TRICK: Does the original series f(x) converge or diverge at the endpoint x = -1?", a: "converge" },
        { q: "(c) TRICK: Does the derivative series f'(x) converge or diverge at the endpoint x = 1?", a: "diverge" }
      ]
    },
    {
      prompt: "We approximate the definite integral $$\\int_{0}^{0.5} e^{-x^2} \\, dx$$ by replacing the integrand with its Maclaurin series up to the $$x^4$$ term.",
      parts: [
        { q: "(a) Write down the integrated polynomial approximation in terms of x.", a: "x - x^3/3 + x^5/10" },
        { q: "(b) Evaluate this fractional polynomial approximation at x = 0.5.", a: "541/1280" },
        { q: "(c) TRICK: Is this approximation an overestimate or an underestimate?", a: "overestimate" }
      ]
    }
  ]
};

function equivalent(student, correct){
    const s = student.trim().toLowerCase();
    const c = correct.trim().toLowerCase();

    if (s === c) return true;

    try {
        const vars = ["x","t","theta"];
        for (let i=1;i<=5;i++){
            const scope = {
                x: i+0.3,
                t: i+0.7,
                theta: i/3,
                pi: Math.PI,
                e: Math.E
            };
            const sv = math.evaluate(student, scope);
            const cv = math.evaluate(correct, scope);
            if (Math.abs(sv-cv) > 1e-6) return false;
        }
        return true;
    } catch {
        return false;
    }
}

function renderQuestion(){

    const promptDiv =
        document.getElementById("prompt");

    const partsDiv =
        document.getElementById("parts");

    promptDiv.innerHTML =
        currentQuestion.prompt;

    partsDiv.innerHTML = "";

    currentQuestion.parts.forEach((p,i)=>{

        const div=document.createElement("div");

        div.className =
            "part" + (i>0 ? " hidden" : "");

        div.id="part"+i;

        div.innerHTML=`
            <p>${p.q}</p>

            <input id="input${i}" />

            <button onclick="grade(${i})">
                Check
            </button>

            <span id="feedback${i}"></span>
        `;

        partsDiv.appendChild(div);
    });

    MathJax.typesetPromise();
}

function grade(i){
    possible++;
    const ans=document.getElementById("input"+i).value;
    const correct=currentQuestion.parts[i].a;

    const ok=equivalent(ans,correct);

    document.getElementById("feedback"+i).innerHTML =
      ok ? '<span class="correct">✓ Correct</span>' :
           '<span class="incorrect">✗ Try Again</span>';

    if(ok){
        score++;
        if(document.getElementById("part"+(i+1)))
            document.getElementById("part"+(i+1)).classList.remove("hidden");
    }

    document.getElementById("points")
        .textContent = score;

    document.getElementById("possibleScore")
        .textContent = possible;
}

function newQuestion(){
    const bank=banks[unitSelect.value];
    currentQuestion=bank[Math.floor(Math.random()*bank.length)];
    renderQuestion();
}

newQuestion();